# Generated by Django 5.2.4 on 2025-08-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bpo_project_bpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='bpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.bpo'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
